name: Sync

on:
  # Daily at 02:00 UTC
  schedule:
    - cron: "0 2 * * *"
  # Manual trigger
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Python & dependencies
        run: uv sync --frozen

      - name: Run sync script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          # PROFILE and folder lists are non-sensitive configuration values.
          # Store them as repository/organization variables and access via vars.
          PROFILE: ${{ vars.PROFILE }}
          PROFILE_0_FOLDERS: ${{ vars.PROFILE_0_FOLDERS }}
          PROFILE_1_FOLDERS: ${{ vars.PROFILE_1_FOLDERS }}
          PROFILE_2_FOLDERS: ${{ vars.PROFILE_2_FOLDERS }}
          PROFILE_3_FOLDERS: ${{ vars.PROFILE_3_FOLDERS }}
        run: uv run python main.py
